CREATE TABLE t_zzs_czsygdgdzc (
`czsygdgdzc_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`ssqj` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '所属期间',
`zcbm` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '资产编码',
`zclb` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '资产类别',
`zcms` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '资产描述',
`sl` decimal(20, 2) COMMENT '数量',
`zbhrq` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '资本化日期',
`zjnx` decimal(20, 2) COMMENT '折旧年限',
`zjff` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '折旧方法',
`yz` decimal(20, 2) COMMENT '原值',
`ljzj` decimal(20, 2) COMMENT '累计折旧',
`jzzb` decimal(20, 2) COMMENT '减值准备',
`zmjz` decimal(20, 2) COMMENT '账面价值',
`czrq` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '处置日期',
`kjfplx` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '开具发票类型',
`cshsjghcsssddxj` decimal(20, 2) COMMENT '出售含税价格或出售时收到的现金',
`jsff` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '计税方法',
`syslhzsl` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '适用税率或征收率',
`csjgbhsje` decimal(20, 2) COMMENT '出售价格
（不含税金额）',
`ynse` decimal(20, 2) COMMENT '应纳税额',
`jse` decimal(20, 2) COMMENT '减税额',
`yjse` decimal(20, 2) COMMENT '应缴税额',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`group_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`group_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`czsygdgdzc_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '处置使用过的固定资产';
