DROP TABLE IF EXISTS t_cxs_dzzcsykmmxb;
DROP TABLE IF EXISTS t_cxs_cyhjsfmx;
DROP TABLE IF EXISTS t_cxs_ssyhjjsqktjb;
DROP TABLE IF EXISTS t_cxs_qlcsyb;
DROP TABLE IF EXISTS t_cxs_dzzcsykmhzb;
DROP TABLE IF EXISTS t_cxs_czhjsfmx;
DROP TABLE IF EXISTS t_cxs_dzzctz;
DROP TABLE IF EXISTS t_cxs_cyhjtdsys;
DROP TABLE IF EXISTS t_cxs_jcxxb ;
DROP TABLE IF EXISTS t_cxs_dzhjsfmx;
DROP TABLE IF EXISTS t_cxs_cyhjfcs;
DROP TABLE IF EXISTS t_cxs_jzbdb;

CREATE TABLE t_cxs_dzzcsykmmxb (
`dzzcsykmmxb_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行（一级分行）',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`ywdzss_5360012` decimal(20, 2) COMMENT '以物抵债损失_5360012',
`jtddzzcjzzb_5340801` decimal(20, 2) COMMENT '计提的抵债资产减值准备_5340801',
`dzzczjsr_zzssl005_5180201` decimal(20, 2) COMMENT '抵债资产租金收入_增值税税率0.05_5180201',
`dzzczjsr_zzssl009_5180202` decimal(20, 2) COMMENT '抵债资产租金收入_增值税税率0.09_5180202',
`dzzcywzc_5400100` decimal(20, 2) COMMENT '抵债资产业务支出_5400100',
`ygyjzjlqqbdjrqtzhsydgqtztzsy_fjrfss_51400024` decimal(20, 2) COMMENT '以公允价值计量且其变动计入其他综合收益的股权投资投资收益_非金融非上市_51400024',
`ygyjzjlqqbdjrqtzhsydgqtztzsy_ss_51400025` decimal(20, 2) COMMENT '以公允价值计量且其变动计入其他综合收益的股权投资投资收益_上市_51400025',
`ygyjzjlqqbdjrqtzhsydgqtztzsy_jrfss_51400026` decimal(20, 2) COMMENT '以公允价值计量且其变动计入其他综合收益的股权投资投资收益_金融非上市_51400026',
`ygyjzjlqqbdjrdqsydgqtztzsy_fjrfss_51400027` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资投资收益_非金融非上市_51400027',
`ygyjzjlqqbdjrdqsydgqtztzsy_ss_51400028` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资投资收益_上市_51400028',
`ygyjzjlqqbdjrdqsydgqtztzsy_jrfss_51400029` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资投资收益_金融非上市_51400029',
`czdzzcsr_5181303` decimal(20, 2) COMMENT '处置抵债资产收入_5181303',
`czdzzczc_5181306` decimal(20, 2) COMMENT '处置抵债资产支出_5181306',
`jcsy_ygyjzjlqqbdjrdqsydgqtzcz_jrfss_5140017` decimal(20, 2) COMMENT '价差损益_以公允价值计量且其变动计入当期损益的股权投资处置_金融非上市_5140017',
`jcsy_ygyjzjlqqbdjrdqsydgqtzcz_ss_5140018` decimal(20, 2) COMMENT '价差损益_以公允价值计量且其变动计入当期损益的股权投资处置_上市_5140018',
`jcsy_ygyjzjlqqbdjrdqsydgqtzcz_jrfss_5140019` decimal(20, 2) COMMENT '价差损益_以公允价值计量且其变动计入当期损益的股权投资处置_金融非上市_5140019',
`ygyjzjlqqbdjrdqsydqtjrzcgyjzbdsy_5190801` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的其他金融资产公允价值变动损益_5190801',
`ygyjzjlqqbdjrdqsydgqtzgyjzbdsy_ss_5192801` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资公允价值变动损益_上市_5192801',
`ygyjzjlqqbdjrdqsydgqtzgyjzbdsy_fss_5192802` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资公允价值变动损益_非上市_5192802',
`wfplrqtbd_czygyjzjlqqbdjrqtzhsydqygj_3120301` decimal(20, 2) COMMENT '未分配利润其他变动_处置以公允价值计量且其变动计入其他综合收益的权益工具_3120301',
`hj` decimal(20, 2) COMMENT '合计',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`dzzcsykmmxb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '抵债资产损益科目明细表';


CREATE TABLE t_cxs_cyhjsfmx (
`cyhjsfmx_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行（一级分行）',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`cyhjsfznjjfk_fcs` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_房产税',
`cyhjsfznjjfk_tdsys` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_土地使用税',
`cyhjsfznjjfk_zjdsrzzs` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_租金等收入增值税',
`cyhjsfznjjfk_sfxj` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_税费小计',
`cyhjsfznjjfk_znj` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_滞纳金',
`cyhjsfznjjfk_fk` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_罚款',
`cyhjsfznjjfk_sfznjjfkhj` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_税费滞纳金及罚款合计',
`cyhjwxcbfy_cnf` decimal(20, 2) COMMENT '持有环节我行成本费用_采暖费',
`cyhjwxcbfy_ktjcf` decimal(20, 2) COMMENT '持有环节我行成本费用_空调基础费',
`cyhjwxcbfy_wxfwf` decimal(20, 2) COMMENT '持有环节我行成本费用_维修服务费',
`cyhjwxcbfy_wyglf` decimal(20, 2) COMMENT '持有环节我行成本费用_物业管理费',
`cyhjwxcbfy_dzxfyft` decimal(20, 2) COMMENT '持有环节我行成本费用_大中修费用分摊',
`cyhjwxcbfy_qt` decimal(20, 2) COMMENT '持有环节我行成本费用_其他',
`cyhjwxcbfy_cbfyxj` decimal(20, 2) COMMENT '持有环节我行成本费用_成本费用小计',
`cyhjsrjxgsfhj_yssrbhsje` decimal(20, 2) COMMENT '持有环节收入及相关税费合计_已收收入不含税金额',
`cyhjsrjxgsfhj_yssrse` decimal(20, 2) COMMENT '持有环节收入及相关税费合计_已收收入税额',
`cyhjsrjxgsfhj_srhjjshj` decimal(20, 2) COMMENT '持有环节收入及相关税费合计_收入合计价税合计',
`cyhjszje` decimal(20, 2) COMMENT '持有环节收支净额',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`cyhjsfmx_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '持有环节税费明细';


CREATE TABLE t_cxs_ssyhjjsqktjb (
`ssyhjjsqktjb_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行（一级分行）',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`jsjndfkhhddjl_zqdsjrwwxwxdfycqrsfjsdsf` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到税局认为我行无需垫付原产权人税费减少的税费',
`jsjndfkhhddjl_zqdyhdtdzzsjsfsjstdzzs` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到优惠的土地增值税计税方式减少土地增值税',
`jsjndfkhhddjl_swjgyyqdffdzhjsfjznj_zqhwxdf` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_税务机关原要求垫付非抵债环节税费及滞纳金_争取后无需垫付',
`jsjndfkhhddjl_zqdwsygdzckmddzzccyqjzmfcsd` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到未使用固定资产科目的抵债资产持有期间暂免房产税等',
`jsjndfkhhddjl_zqdswjgtyadzghszwnsywfssjdzhjqbskmyj` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到税务机关同意按抵债过户时作为纳税义务发生时间，抵债环节全部税款免予加收滞纳金、减少缴纳房产税和土地使用税',
`jsjndfkhhddjl_zqdasszgfdgdzzzbcg5ndskjznj` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到按税收征管法的规定只追征不超过5年的税款及滞纳金',
`jsjndfkhhddjl_zqddzhjwxjnyhs` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到抵债环节无需缴纳印花税',
`jsjndfkhhddjl_zqdmyjsfk` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到免予加收罚款',
`jsjndfkhhddjl_zqdsjhycqrkjzyfpdkzzsjfj` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到税局或原产权人开具专用发票抵扣增值税及附加',
`jsjndfkhhddjl_zqdyhqddzzcsjnhdjsfddflcbf` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到印花取得抵债资产时缴纳或代缴税费的地方留成部分',
`jsjndfkhhddjl_yjzjswchjsje` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_预计中介税务筹划节税金额',
`jsjndfkhhddjl_qt` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '减少缴纳的罚款和获得的奖励_其他',
`jsjndfkhhddjl_xj` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_小计',
`zjjndfk_swchfy` decimal(20, 2) COMMENT '增加缴纳的罚款_税务筹划费用',
`zjjndfk_wxcdycqrfdzhjfkbksqkczj25qysds` decimal(20, 2) COMMENT '增加缴纳的罚款_我行承担原产权人非抵债环节罚款不可税前扣除增加25%企业所得税',
`zjjndfk_wxcdycqrdzhjfkbksqkczj25qysds` decimal(20, 2) COMMENT '增加缴纳的罚款_我行承担原产权人抵债环节罚款不可税前扣除增加25%企业所得税',
`zjjndfk_wxfdskdfkbksqkc25qysds` decimal(20, 2) COMMENT '增加缴纳的罚款_我行法定税款的罚款不可税前扣除25%企业所得税',
`zjjndfk_xj` decimal(20, 2) COMMENT '增加缴纳的罚款_小计',
`sfznjjfkjlzjjehj` decimal(20, 2) COMMENT '税费滞纳金及罚款奖励增减净额合计',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`ssyhjjsqktjb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '税收优惠及节税情况统计表';


CREATE TABLE t_cxs_qlcsyb (
`qlcsyb_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行一级分行',
`dzzcbh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`dzjehs` decimal(20, 2) COMMENT '抵债金额含税',
`dzhjjxs` decimal(20, 2) COMMENT '抵债环节进项税',
`dzjebhdkjxs` decimal(20, 2) COMMENT '抵债金额不含抵扣进项税',
`cddzhjfwxfdsfjfk` decimal(20, 2) COMMENT '承担抵债环节非我行法定税费及罚款',
`dzhjwxfdsfjfk` decimal(20, 2) COMMENT '抵债环节我行法定税费及罚款',
`cyhjsrhs` decimal(20, 2) COMMENT '持有环节收入含税',
`qtsr` decimal(20, 2) COMMENT '其他收入',
`cyhjcbfy` decimal(20, 2) COMMENT '持有环节成本费用',
`cyhjsfznjjfkzc` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款支出',
`czskjehsyjwfybkmfcdd` decimal(20, 2) COMMENT '处置收款金额含所有价外费用包括买方承担的',
`czhjwxfdsf` decimal(20, 2) COMMENT '处置环节我行法定税费',
`cdczhjdsffy` decimal(20, 2) COMMENT '承担处置环节第三方费用',
`dzzcqbhjzhsy` decimal(20, 2) COMMENT '抵债资产全部环节综合损益',
`czhjjxjl` decimal(20, 2) COMMENT '处置环节净现金流',
`chzbj` decimal(20, 2) COMMENT '冲回准备金',
`czdqbbsy` decimal(20, 2) COMMENT '处置当期报表损益',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`qlcsyb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '全流程损益表';


CREATE TABLE t_cxs_dzzcsykmhzb (
`dzzcsykmhzb_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`kmdm` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '科目代码',
`ywdzss_5360012` decimal(20, 2) COMMENT '以物抵债损失_5360012',
`jtddzzcjzzb_5340801` decimal(20, 2) COMMENT '计提的抵债资产减值准备_5340801',
`dzzczjsrzzssl005_5180201` decimal(20, 2) COMMENT '抵债资产租金收入增值税税率005_5180201',
`dzzczjsrzzssl009_5180202` decimal(20, 2) COMMENT '抵债资产租金收入增值税税率009_5180202',
`dzzcywzc_5400100` decimal(20, 2) COMMENT '抵债资产业务支出_5400100',
`ygyjzjlqqbdjrqtzhsydgqtztzsyfjrfss_51400024` decimal(20, 2) COMMENT '以公允价值计量且其变动计入其他综合收益的股权投资投资收益非金融非上市_51400024',
`ygyjzjlqqbdjrqtzhsydgqtztzsyss_51400025` decimal(20, 2) COMMENT '以公允价值计量且其变动计入其他综合收益的股权投资投资收益上市_51400025',
`ygyjzjlqqbdjrqtzhsydgqtztzsyjrfss_51400026` decimal(20, 2) COMMENT '以公允价值计量且其变动计入其他综合收益的股权投资投资收益金融非上市_51400026',
`ygyjzjlqqbdjrdqsydgqtztzsyfjrfss_51400027` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资投资收益非金融非上市_51400027',
`ygyjzjlqqbdjrdqsydgqtztzsyss_51400028` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资投资收益上市_51400028',
`ygyjzjlqqbdjrdqsydgqtztzsyjrfss_51400029` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资投资收益金融非上市_51400029',
`czdzzcsr_5181303` decimal(20, 2) COMMENT '处置抵债资产收入_5181303',
`czdzzczc_5181306` decimal(20, 2) COMMENT '处置抵债资产支出_5181306',
`jcsyygyjzjlqqbdjrdqsydgqtzczjrfss_5140017` decimal(20, 2) COMMENT '价差损益以公允价值计量且其变动计入当期损益的股权投资处置金融非上市_5140017',
`jcsyygyjzjlqqbdjrdqsydgqtzczss_5140018` decimal(20, 2) COMMENT '价差损益以公允价值计量且其变动计入当期损益的股权投资处置上市_5140018',
`jcsyygyjzjlqqbdjrdqsydgqtzczjrfss_5140019` decimal(20, 2) COMMENT '价差损益以公允价值计量且其变动计入当期损益的股权投资处置金融非上市_5140019',
`ygyjzjlqqbdjrdqsydqtjrzcgyjzbdsy_5190801` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的其他金融资产公允价值变动损益_5190801',
`ygyjzjlqqbdjrdqsydgqtzgyjzbdsyss_5192801` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资公允价值变动损益上市_5192801',
`ygyjzjlqqbdjrdqsydgqtzgyjzbdsyfss_5192802` decimal(20, 2) COMMENT '以公允价值计量且其变动计入当期损益的股权投资公允价值变动损益非上市_5192802',
`wfplrqtbdczygyjzjlqqbdjrqtzhsydqygj_3120301` decimal(20, 2) COMMENT '未分配利润其他变动处置以公允价值计量且其变动计入其他综合收益的权益工具_3120301',
`hj` decimal(20, 2) COMMENT '合计',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`dzzcsykmhzb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '抵债资产损益科目汇总表';


CREATE TABLE t_cxs_czhjsfmx (
`czhjsfmx_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行（一级分行）',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`sfznjjfkhj_zzs` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_增值税',
`sfznjjfkhj_cswhjss` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_城市维护建设税',
`sfznjjfkhj_jyffj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_教育费附加',
`sfznjjfkhj_dfjyfj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_地方教育附加',
`sfznjjfkhj_dwf` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_堤围费',
`sfznjjfkhj_yhs` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_印花税',
`sfznjjfkhj_tdzzs` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_土地增值税',
`sfznjjfkhj_sfxj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_税费小计',
`sfznjjfkhj_znj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_滞纳金',
`sfznjjfkhj_fk` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_罚款',
`sfznjjfkhj_sfznjjfkhj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_税费滞纳金及罚款合计',
`sfznjjfkhj_qzwxcddfsfznjjfk` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_其中我行承担垫付税费滞纳金及罚款',
`sfznjjfkhj_qzczhjmfcdsfznjjfk` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_其中处置环节买房承担税费滞纳金及罚款',
`sfznjjfkhj_ys` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_验算',
`czhjdsffy_pgf` decimal(20, 2) COMMENT '处置环节第三方费用_评估费',
`czhjdsffy_tff` decimal(20, 2) COMMENT '处置环节第三方费用_腾房费',
`czhjdsffy_lsf` decimal(20, 2) COMMENT '处置环节第三方费用_律师费',
`czhjdsffy_swchfy` decimal(20, 2) COMMENT '处置环节第三方费用_税务筹划费用',
`czhjdsffy_qtfy` decimal(20, 2) COMMENT '处置环节第三方费用_其他费用',
`czhjdsffy_czhjfyxj` decimal(20, 2) COMMENT '处置环节第三方费用_处置环节费用小计',
`czhjdsffy_qzwxcdfy` decimal(20, 2) COMMENT '处置环节第三方费用_其中我行承担费用',
`czhjdsffy_qzdfcdfy` decimal(20, 2) COMMENT '处置环节第三方费用_其中对方承担费用',
`czhjdsffy_ys` decimal(20, 2) COMMENT '处置环节第三方费用_验算',
`czhjsfznjjfkdsffyhj` decimal(20, 2) COMMENT '处置环节税费滞纳金及罚款第三方费用合计',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`czhjsfmx_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '处置环节税费明细';


CREATE TABLE t_cxs_dzzctz (
`dzzctz_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zxzgywbm` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '总行主管业务部门',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`jjh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '借据号',
`qy` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '区域',
`fb` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '分部',
`ywjgbm` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '业务经管部门',
`zghr` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '主管户人',
`zwgsfhyjfh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行一级分行',
`zwgswdmc` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属网点名称',
`dzfs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债方式',
`pjshdzxysxr` datetime COMMENT '判决书或抵债协议生效日',
`qdcqzssj` datetime COMMENT '取得产权证书时间',
`dzzcdl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产大类',
`dzzcmxfl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产明细分类',
`sl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '数量',
`fcjzmjpfm` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房产建筑面积平方米',
`tdxz` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '土地性质',
`tdyt` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '土地用途',
`tdnsdj` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '土地纳税等级',
`tdmjm` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '土地面积亩',
`cyqk` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '持有情况',
`cyqkzyqkzyrmc` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '持有情况占用情况占用人名称',
`cyqkzyqksfypjcd` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '持有情况占用情况是否有判决裁定',
`fcszsf` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房产所在省份',
`fcszs` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房产所在市',
`fcszxssq` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房产所在县市属区',
`fcszxz` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房产所在乡镇',
`sfsyjzz` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '是否属于建制镇',
`dzzcmc` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`fczldzgswjg` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房产坐落地主管税务机关',
`cqssfhzgswjg` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '产权所属分行主管税务机关',
`ycqr` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人',
`dzzcjkrmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产借款人名称',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`dzzctz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '抵债资产台账';


CREATE TABLE t_cxs_cyhjtdsys (
`cyhjtdsys_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行一级分行',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`tdsybh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '土地税源编号',
`dh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '地号',
`tdsyzbh` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '土地使用证编号',
`tdmc` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '土地名称',
`tdzldz` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '土地坐落地址',
`skssqq` datetime COMMENT '税款所属期起',
`skssqz` datetime COMMENT '税款所属期止',
`zytdmj` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '占用土地面积',
`nyjnse` decimal(20, 2) COMMENT '年应缴纳税额',
`pzjmnse` decimal(20, 2) COMMENT '批准减免年税额',
`nsjyjse` decimal(20, 2) COMMENT '年实际应交税额',
`fk` decimal(20, 2) COMMENT '罚款',
`znj` decimal(20, 2) COMMENT '滞纳金',
`bz` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '备注',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`cyhjtdsys_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '持有环节土地使用税';


CREATE TABLE t_cxs_jcxxb  (
`jcxxb _id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行',
`zwgsfhmc` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行名称',
`dzzcjbqk_zxzgywbm` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_总行主管业务部门',
`dzzcjbqk_dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产编号',
`dzzcjbqk_jjh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_借据号',
`dzzcjbqk_qy` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_区域',
`dzzcjbqk_fb` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_分部',
`dzzcjbqk_ywjgbm` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_业务经管部门',
`dzzcjbqk_zghr` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_主管户人',
`dzzcjbqk_dzfs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债方式',
`dzzcjbqk_pjshdzxysxr` datetime COMMENT '抵债资产基本情况_判决书或抵债协议生效日',
`dzzcjbqk_qdcqzssj` datetime COMMENT '抵债资产基本情况_取得产权证书时间',
`dzzcjbqk_dzzcdl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产大类',
`dzzcjbqk_dzzcmxfl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产明细分类',
`dzzcjbqk_sl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_数量',
`dzzcjbqk_fcjzmj` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产建筑面积',
`dzzcjbqk_tdxz` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_土地性质',
`dzzcjbqk_tdyt` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_土地用途',
`dzzcjbqk_tdnsdj` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_土地纳税等级',
`dzzcjbqk_tdmj` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_土地面积',
`dzzcjbqk_cyqk` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_持有情况',
`dzzcjbqk_cyqkzyqk_zyrmc` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_持有情况占用情况_占用人名称',
`dzzcjbqk_cyqkzyqk_sfypjcd` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_持有情况占用情况_是否有判决裁定',
`dzzcjbqk_fcszsf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产所在省份',
`dzzcjbqk_fcszs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产所在市',
`dzzcjbqk_fcszxssq` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产所在县市属区',
`dzzcjbqk_fcszxz` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产所在乡镇',
`dzzcjbqk_sfsyjzz` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_是否属于建制镇',
`dzzcjbqk_dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产名称',
`dzzcjbqk_fczldzgswjg` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产坐落地主管税务机关',
`dzzcjbqk_cqssfhzgswjg` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_产权所属分行主管税务机关',
`dzzcjbqk_ycqr` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_原产权人',
`dzzcjbqk_dzzcjkrmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产借款人名称',
`fyjzwrgt_cdssfmqwxcdycqrsf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_裁定书是否明确我行承担原产权人税费',
`fyjzwrgt_cdsmmqsfcdfsfydycqrsfrdkj` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_裁定书没明确税费承担方时法院对原产权人税费认定口径',
`fyjzwrgt_dfycqrsfnfssqq` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_垫付原产权人税费能否诉讼确权',
`fyjzwrgt_ycqrxz` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_原产权人现状',
`fyjzwrgt_nfqdycqrgrcbzl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_能否取得原产权人购入成本资料',
`fyjzwrgt_bnqdycqrgrcbzldyy` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_不能取得原产权人购入成本资料的原因',
`msrgt_czhjsfcdfs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '买受人沟通_处置环节税费承担方式',
`swjgkj_zqdddzzcssyhzchyljskjjzfjl` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_争取到的抵债资产税收优惠政策和有利计税口径及政府奖励',
`swjgkj_swjgdycqrsfcdfrdkj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_税务机关对原产权人税费承担方认定口径',
`swjgkj_wxcdycqrsfznjjfknfsqkc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_我行承担原产权人税费滞纳金及罚款能否税前扣除',
`swjgkj_dzhjwfqdfpczszzsjtdzzsjskj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_抵债环节无法取得发票处置时增值税及土地增值税计税口径',
`swjgkj_dzhjwfqdfpczsqysdssqkckj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_抵债环节无法取得发票处置时企业所得税税前扣除口径',
`swjgkj_dzhjnsywfssjrdkj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_抵债环节纳税义务发生时间认定口径',
`swjgkj_cyhjnsywfssjrdkj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_持有环节纳税义务发生时间认定口径',
`swjgkj_tdzzsjsfs` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_土地增值税计税方式',
`swjgkj_zzsjsfs` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_增值税计税方式',
`swjgkj_zzsjskj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_增值税计税口径',
`swjgkj_qsjskj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_契税计税口径',
`swjgkj_yhsjskj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_印花税计税口径',
`swjgsfyqdjyzwrfdzhjsf_sfyqdjqysds` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否要求垫交企业所得税',
`swjgsfyqdjyzwrfdzhjsf_sfyqdjfcs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否要求垫交房产税',
`swjgsfyqdjyzwrfdzhjsf_sfyqdjtdsys` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否要求垫交土地使用税',
`swjgsfyqdjyzwrfdzhjsf_sfdjtdcrj` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否垫交土地出让金',
`swjgsfyqdjyzwrfdzhjsf_sfdjtdgf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否垫交土地规费',
`swjgsfyqdjyzwrfdzhjsf_sfyqthyzwrqddzfbtjld` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否要求退回原债务人取得的政府补贴奖励等',
`swjgsfyqdjyzwrfdzhjsf_sfjqtsf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否交其他税费',
`swjgsfyqdjyzwrfdzhjsf_smsjyqdjyzwrfdzhjsfdzcyj` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_说明税局要求垫交原债务人非抵债环节税费的政策依据',
`ycqrgt_sfdfhcdsdqjwyglfd` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人沟通_是否垫付或承担水电气及物业管理费等',
`bz1` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '备注1',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`jcxxb _id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '基础信息表 ';


CREATE TABLE t_cxs_dzhjsfmx (
`dzhjsfmx_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行一级分行',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`ycqrfdzhjsf_qysds` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_企业所得税',
`ycqrfdzhjsf_fcs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_房产税',
`ycqrfdzhjsf_tdsys` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_土地使用税',
`ycqrfdzhjsf_tdcrj` decimal(20, 2) COMMENT '原产权人非抵债环节税费_土地出让金',
`ycqrfdzhjsf_tdgf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_土地规费',
`ycqrfdzhjsf_thyzwrqddzfbtjld` decimal(20, 2) COMMENT '原产权人非抵债环节税费_退回原债务人取得的政府补贴奖励等',
`ycqrfdzhjsf_qtsfqsmjtsfmc` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_其他税费请说明具体税费名称',
`ycqrfdzhjsf_qtsfsm` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_其他税费说明',
`ycqrfdzhjsf_dfhcdsdqjwyglf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_垫付或承担水电气及物业管理费',
`ycqrfdzhjsf_sfxj` decimal(20, 2) COMMENT '原产权人非抵债环节税费_税费小计',
`ycqrfdzhjsf_znj` decimal(20, 2) COMMENT '原产权人非抵债环节税费_滞纳金',
`ycqrfdzhjsf_fk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_罚款',
`ycqrfdzhjsf_sfznjjfkhj` decimal(20, 2) COMMENT '原产权人非抵债环节税费_税费滞纳金及罚款合计',
`ycqrfdzhjsf_qzyzwrzxcdsfznjjfk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_其中原债务人自行承担税费滞纳金及罚款',
`ycqrfdzhjsf_qzswjggqyzwrzxcdsfznjjfk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_其中税务机关挂起原债务人自行承担税费滞纳金及罚款',
`ycqrfdzhjsf_qzwxcddfsfznjjfk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_其中我行承担垫付税费滞纳金及罚款',
`ycqrfdzhjsf_qzczhjmfcdsfznjjfk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_其中处置环节买方承担税费滞纳金及罚款',
`ycqrfdzhjsf_ys` decimal(20, 2) COMMENT '原产权人非抵债环节税费_验算',
`dzhjfdmfsfjfk_grsds` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_个人所得税',
`dzhjfdmfsfjfk_zzs` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_增值税',
`dzhjfdmfsfjfk_cswhjss` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_城市维护建设税',
`dzhjfdmfsfjfk_jyffj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_教育费附加',
`dzhjfdmfsfjfk_dfjyfj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_地方教育附加',
`dzhjfdmfsfjfk_dwf` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_堤围费',
`dzhjfdmfsfjfk_yhs` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_印花税',
`dzhjfdmfsfjfk_tdzzs` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_土地增值税',
`dzhjfdmfsfjfk_sfxj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_税费小计',
`dzhjfdmfsfjfk_znj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_滞纳金',
`dzhjfdmfsfjfk_fk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_罚款',
`dzhjfdmfsfjfk_sfznjjfkhj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_税费滞纳金及罚款合计',
`dzhjfdmfsfjfk_qzyzwrzxcdsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_其中原债务人自行承担税费滞纳金及罚款',
`dzhjfdmfsfjfk_qzswjggqyzwrsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_其中税务机关挂起原债务人税费滞纳金及罚款',
`dzhjfdmfsfjfk_qzwxcddfsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_其中我行承担垫付税费滞纳金及罚款',
`dzhjfdmfsfjfk_qzczhjmfcdsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_其中处置环节买方承担税费滞纳金及罚款',
`dzhjfdmfsfjfk_ys` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_验算',
`dzhjfdwxsfjfk_qs3` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_契税3',
`dzhjfdwxsfjfk_yhs005` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_印花税005',
`dzhjfdwxsfjfk_sfxj` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_税费小计',
`dzhjfdwxsfjfk_znj` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_滞纳金',
`dzhjfdwxsfjfk_fk` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_罚款',
`dzhjfdwxsfjfk_sfznjjfkhj` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_税费滞纳金及罚款合计',
`dzhjfdwxsfjfk_qzwxcdsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_其中我行承担税费滞纳金及罚款',
`dzhjfdwxsfjfk_qzczhjmfcdsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_其中处置环节买方承担税费滞纳金及罚款',
`dzhjfdwxsfjfk_ys` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_验算',
`dzhjdsffy_pgf` decimal(20, 2) COMMENT '抵债环节第三方费用_评估费',
`dzhjdsffy_tff` decimal(20, 2) COMMENT '抵债环节第三方费用_腾房费',
`dzhjdsffy_lsf` decimal(20, 2) COMMENT '抵债环节第三方费用_律师费',
`dzhjdsffy_swchfy` decimal(20, 2) COMMENT '抵债环节第三方费用_税务筹划费用',
`dzhjdsffy_qtfy` decimal(20, 2) COMMENT '抵债环节第三方费用_其他费用',
`dzhjdsffy_dzhjfyxj` decimal(20, 2) COMMENT '抵债环节第三方费用_抵债环节费用小计',
`dzhjdsffy_qzwxcdfy` decimal(20, 2) COMMENT '抵债环节第三方费用_其中我行承担费用',
`dzhjdsffy_qzczhjmfcdfy` decimal(20, 2) COMMENT '抵债环节第三方费用_其中处置环节买方承担费用',
`dzhjdsffy_ys` decimal(20, 2) COMMENT '抵债环节第三方费用_验算',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`dzhjsfmx_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '抵债环节税费明细';


CREATE TABLE t_cxs_cyhjfcs (
`cyhjfcs_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh001` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行一级分行-0.01',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`fcsybh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房产税源编号',
`fdczh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房地产证号',
`fcdz` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房产地址',
`fdcmc` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '房地产名称',
`skssqq` datetime COMMENT '税款所属期起',
`skssqz` datetime COMMENT '税款所属期止',
`fcyz` decimal(20, 2) COMMENT '房产原值',
`jsyz` decimal(20, 2) COMMENT '计税余值',
`cjjzsysl` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '从价计征适用税率',
`yzj` decimal(20, 2) COMMENT '月租金',
`jsfs` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '计税方式',
`czjzsysl` decimal(20, 2) COMMENT '从租计征适用税率',
`nyjnse` decimal(20, 2) COMMENT '年应缴纳税额',
`pzjmnse` decimal(20, 2) COMMENT '批准减免年税额',
`nsjyjse` decimal(20, 2) COMMENT '年实际应交税额',
`fk` decimal(20, 2) COMMENT '罚款',
`znj` decimal(20, 2) COMMENT '滞纳金',
`bz` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '备注',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`cyhjfcs_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '持有环节房产税';


CREATE TABLE t_cxs_jzbdb (
`jzbdb_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`dzzcjkrmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产借款人名称',
`pjshdzxysxr` datetime COMMENT '判决书或抵债协议生效日',
`dzrzrq` datetime COMMENT '抵债入账日期',
`kmdm` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '科目代码',
`kmmc` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '科目名称',
`bz` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '币种',
`cdje` decimal(20, 2) COMMENT '裁定金额',
`rzje_hsyb` decimal(20, 2) COMMENT '入账金额_含税原币',
`ydkjxse` decimal(20, 2) COMMENT '已抵扣进项税额',
`rzje_bhszrmb` decimal(20, 2) COMMENT '入账金额_不含税折人民币',
`jzgyjzbdkmdm` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '减值/公允价值变动科目代码',
`jzgyjzbdje` decimal(20, 2) COMMENT '减值/公允价值变动金额',
`dzzczmje` decimal(20, 2) COMMENT '抵债资产账面净额',
`czsj` datetime COMMENT '处置时间',
`czbfrzjz` decimal(20, 2) COMMENT '处置部分入账价值',
`czhskx` decimal(20, 2) COMMENT '处置回收款项',
`czcjzbgyjzbd` decimal(20, 2) COMMENT '处置冲减准备/公允价值变动',
`czdzzcsy` decimal(20, 2) COMMENT '处置抵债资产损益',
`dzzcye` decimal(20, 2) COMMENT '抵债资产余额',
`yqts` decimal(20, 2) COMMENT '逾期天数',
`sfyq` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '是否逾期',
`jsRWAfl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '计算RWA分类',
`jsxs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '计算系数',
`qmRWAzy` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '期末RWA占用',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`jzbdb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '价值变动表';


