CREATE TABLE t_cxs_czhjsfmx (
`czhjsfmx_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行（一级分行）',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`sfznjjfkhj_zzs` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_增值税',
`sfznjjfkhj_cswhjss` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_城市维护建设税',
`sfznjjfkhj_jyffj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_教育费附加',
`sfznjjfkhj_dfjyfj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_地方教育附加',
`sfznjjfkhj_dwf` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_堤围费',
`sfznjjfkhj_yhs` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_印花税',
`sfznjjfkhj_tdzzs` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_土地增值税',
`sfznjjfkhj_sfxj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_税费小计',
`sfznjjfkhj_znj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_滞纳金',
`sfznjjfkhj_fk` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_罚款',
`sfznjjfkhj_sfznjjfkhj` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_税费滞纳金及罚款合计',
`sfznjjfkhj_qzwxcddfsfznjjfk` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_其中我行承担垫付税费滞纳金及罚款',
`sfznjjfkhj_qzczhjmfcdsfznjjfk` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_其中处置环节买房承担税费滞纳金及罚款',
`sfznjjfkhj_ys` decimal(20, 2) COMMENT '税费滞纳金及罚款合计_验算',
`czhjdsffy_pgf` decimal(20, 2) COMMENT '处置环节第三方费用_评估费',
`czhjdsffy_tff` decimal(20, 2) COMMENT '处置环节第三方费用_腾房费',
`czhjdsffy_lsf` decimal(20, 2) COMMENT '处置环节第三方费用_律师费',
`czhjdsffy_swchfy` decimal(20, 2) COMMENT '处置环节第三方费用_税务筹划费用',
`czhjdsffy_qtfy` decimal(20, 2) COMMENT '处置环节第三方费用_其他费用',
`czhjdsffy_czhjfyxj` decimal(20, 2) COMMENT '处置环节第三方费用_处置环节费用小计',
`czhjdsffy_qzwxcdfy` decimal(20, 2) COMMENT '处置环节第三方费用_其中我行承担费用',
`czhjdsffy_qzdfcdfy` decimal(20, 2) COMMENT '处置环节第三方费用_其中对方承担费用',
`czhjdsffy_ys` decimal(20, 2) COMMENT '处置环节第三方费用_验算',
`czhjsfznjjfkdsffyhj` decimal(20, 2) COMMENT '处置环节税费滞纳金及罚款第三方费用合计',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`czhjsfmx_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '处置环节税费明细';
