CREATE TABLE t_cxs_ssyhjjsqktjb (
`ssyhjjsqktjb_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行（一级分行）',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`jsjndfkhhddjl_zqdsjrwwxwxdfycqrsfjsdsf` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到税局认为我行无需垫付原产权人税费减少的税费',
`jsjndfkhhddjl_zqdyhdtdzzsjsfsjstdzzs` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到优惠的土地增值税计税方式减少土地增值税',
`jsjndfkhhddjl_swjgyyqdffdzhjsfjznj_zqhwxdf` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_税务机关原要求垫付非抵债环节税费及滞纳金_争取后无需垫付',
`jsjndfkhhddjl_zqdwsygdzckmddzzccyqjzmfcsd` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到未使用固定资产科目的抵债资产持有期间暂免房产税等',
`jsjndfkhhddjl_zqdswjgtyadzghszwnsywfssjdzhjqbskmyj` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到税务机关同意按抵债过户时作为纳税义务发生时间，抵债环节全部税款免予加收滞纳金、减少缴纳房产税和土地使用税',
`jsjndfkhhddjl_zqdasszgfdgdzzzbcg5ndskjznj` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到按税收征管法的规定只追征不超过5年的税款及滞纳金',
`jsjndfkhhddjl_zqddzhjwxjnyhs` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到抵债环节无需缴纳印花税',
`jsjndfkhhddjl_zqdmyjsfk` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到免予加收罚款',
`jsjndfkhhddjl_zqdsjhycqrkjzyfpdkzzsjfj` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到税局或原产权人开具专用发票抵扣增值税及附加',
`jsjndfkhhddjl_zqdyhqddzzcsjnhdjsfddflcbf` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_争取到印花取得抵债资产时缴纳或代缴税费的地方留成部分',
`jsjndfkhhddjl_yjzjswchjsje` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_预计中介税务筹划节税金额',
`jsjndfkhhddjl_qt` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '减少缴纳的罚款和获得的奖励_其他',
`jsjndfkhhddjl_xj` decimal(20, 2) COMMENT '减少缴纳的罚款和获得的奖励_小计',
`zjjndfk_swchfy` decimal(20, 2) COMMENT '增加缴纳的罚款_税务筹划费用',
`zjjndfk_wxcdycqrfdzhjfkbksqkczj25qysds` decimal(20, 2) COMMENT '增加缴纳的罚款_我行承担原产权人非抵债环节罚款不可税前扣除增加25%企业所得税',
`zjjndfk_wxcdycqrdzhjfkbksqkczj25qysds` decimal(20, 2) COMMENT '增加缴纳的罚款_我行承担原产权人抵债环节罚款不可税前扣除增加25%企业所得税',
`zjjndfk_wxfdskdfkbksqkc25qysds` decimal(20, 2) COMMENT '增加缴纳的罚款_我行法定税款的罚款不可税前扣除25%企业所得税',
`zjjndfk_xj` decimal(20, 2) COMMENT '增加缴纳的罚款_小计',
`sfznjjfkjlzjjehj` decimal(20, 2) COMMENT '税费滞纳金及罚款奖励增减净额合计',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`ssyhjjsqktjb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '税收优惠及节税情况统计表';
