CREATE TABLE t_cxs_dzhjsfmx (
`dzhjsfmx_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行一级分行',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`ycqrfdzhjsf_qysds` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_企业所得税',
`ycqrfdzhjsf_fcs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_房产税',
`ycqrfdzhjsf_tdsys` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_土地使用税',
`ycqrfdzhjsf_tdcrj` decimal(20, 2) COMMENT '原产权人非抵债环节税费_土地出让金',
`ycqrfdzhjsf_tdgf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_土地规费',
`ycqrfdzhjsf_thyzwrqddzfbtjld` decimal(20, 2) COMMENT '原产权人非抵债环节税费_退回原债务人取得的政府补贴奖励等',
`ycqrfdzhjsf_qtsfqsmjtsfmc` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_其他税费请说明具体税费名称',
`ycqrfdzhjsf_qtsfsm` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_其他税费说明',
`ycqrfdzhjsf_dfhcdsdqjwyglf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人非抵债环节税费_垫付或承担水电气及物业管理费',
`ycqrfdzhjsf_sfxj` decimal(20, 2) COMMENT '原产权人非抵债环节税费_税费小计',
`ycqrfdzhjsf_znj` decimal(20, 2) COMMENT '原产权人非抵债环节税费_滞纳金',
`ycqrfdzhjsf_fk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_罚款',
`ycqrfdzhjsf_sfznjjfkhj` decimal(20, 2) COMMENT '原产权人非抵债环节税费_税费滞纳金及罚款合计',
`ycqrfdzhjsf_qzyzwrzxcdsfznjjfk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_其中原债务人自行承担税费滞纳金及罚款',
`ycqrfdzhjsf_qzswjggqyzwrzxcdsfznjjfk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_其中税务机关挂起原债务人自行承担税费滞纳金及罚款',
`ycqrfdzhjsf_qzwxcddfsfznjjfk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_其中我行承担垫付税费滞纳金及罚款',
`ycqrfdzhjsf_qzczhjmfcdsfznjjfk` decimal(20, 2) COMMENT '原产权人非抵债环节税费_其中处置环节买方承担税费滞纳金及罚款',
`ycqrfdzhjsf_ys` decimal(20, 2) COMMENT '原产权人非抵债环节税费_验算',
`dzhjfdmfsfjfk_grsds` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_个人所得税',
`dzhjfdmfsfjfk_zzs` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_增值税',
`dzhjfdmfsfjfk_cswhjss` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_城市维护建设税',
`dzhjfdmfsfjfk_jyffj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_教育费附加',
`dzhjfdmfsfjfk_dfjyfj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_地方教育附加',
`dzhjfdmfsfjfk_dwf` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_堤围费',
`dzhjfdmfsfjfk_yhs` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_印花税',
`dzhjfdmfsfjfk_tdzzs` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_土地增值税',
`dzhjfdmfsfjfk_sfxj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_税费小计',
`dzhjfdmfsfjfk_znj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_滞纳金',
`dzhjfdmfsfjfk_fk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_罚款',
`dzhjfdmfsfjfk_sfznjjfkhj` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_税费滞纳金及罚款合计',
`dzhjfdmfsfjfk_qzyzwrzxcdsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_其中原债务人自行承担税费滞纳金及罚款',
`dzhjfdmfsfjfk_qzswjggqyzwrsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_其中税务机关挂起原债务人税费滞纳金及罚款',
`dzhjfdmfsfjfk_qzwxcddfsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_其中我行承担垫付税费滞纳金及罚款',
`dzhjfdmfsfjfk_qzczhjmfcdsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_其中处置环节买方承担税费滞纳金及罚款',
`dzhjfdmfsfjfk_ys` decimal(20, 2) COMMENT '抵债环节法定卖方税费及罚款_验算',
`dzhjfdwxsfjfk_qs3` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_契税3',
`dzhjfdwxsfjfk_yhs005` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_印花税005',
`dzhjfdwxsfjfk_sfxj` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_税费小计',
`dzhjfdwxsfjfk_znj` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_滞纳金',
`dzhjfdwxsfjfk_fk` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_罚款',
`dzhjfdwxsfjfk_sfznjjfkhj` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_税费滞纳金及罚款合计',
`dzhjfdwxsfjfk_qzwxcdsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_其中我行承担税费滞纳金及罚款',
`dzhjfdwxsfjfk_qzczhjmfcdsfznjjfk` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_其中处置环节买方承担税费滞纳金及罚款',
`dzhjfdwxsfjfk_ys` decimal(20, 2) COMMENT '抵债环节法定我行税费及罚款_验算',
`dzhjdsffy_pgf` decimal(20, 2) COMMENT '抵债环节第三方费用_评估费',
`dzhjdsffy_tff` decimal(20, 2) COMMENT '抵债环节第三方费用_腾房费',
`dzhjdsffy_lsf` decimal(20, 2) COMMENT '抵债环节第三方费用_律师费',
`dzhjdsffy_swchfy` decimal(20, 2) COMMENT '抵债环节第三方费用_税务筹划费用',
`dzhjdsffy_qtfy` decimal(20, 2) COMMENT '抵债环节第三方费用_其他费用',
`dzhjdsffy_dzhjfyxj` decimal(20, 2) COMMENT '抵债环节第三方费用_抵债环节费用小计',
`dzhjdsffy_qzwxcdfy` decimal(20, 2) COMMENT '抵债环节第三方费用_其中我行承担费用',
`dzhjdsffy_qzczhjmfcdfy` decimal(20, 2) COMMENT '抵债环节第三方费用_其中处置环节买方承担费用',
`dzhjdsffy_ys` decimal(20, 2) COMMENT '抵债环节第三方费用_验算',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`dzhjsfmx_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '抵债环节税费明细';
