CREATE TABLE t_cxs_cyhjsfmx (
`cyhjsfmx_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行（一级分行）',
`dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`cyhjsfznjjfk_fcs` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_房产税',
`cyhjsfznjjfk_tdsys` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_土地使用税',
`cyhjsfznjjfk_zjdsrzzs` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_租金等收入增值税',
`cyhjsfznjjfk_sfxj` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_税费小计',
`cyhjsfznjjfk_znj` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_滞纳金',
`cyhjsfznjjfk_fk` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_罚款',
`cyhjsfznjjfk_sfznjjfkhj` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款_税费滞纳金及罚款合计',
`cyhjwxcbfy_cnf` decimal(20, 2) COMMENT '持有环节我行成本费用_采暖费',
`cyhjwxcbfy_ktjcf` decimal(20, 2) COMMENT '持有环节我行成本费用_空调基础费',
`cyhjwxcbfy_wxfwf` decimal(20, 2) COMMENT '持有环节我行成本费用_维修服务费',
`cyhjwxcbfy_wyglf` decimal(20, 2) COMMENT '持有环节我行成本费用_物业管理费',
`cyhjwxcbfy_dzxfyft` decimal(20, 2) COMMENT '持有环节我行成本费用_大中修费用分摊',
`cyhjwxcbfy_qt` decimal(20, 2) COMMENT '持有环节我行成本费用_其他',
`cyhjwxcbfy_cbfyxj` decimal(20, 2) COMMENT '持有环节我行成本费用_成本费用小计',
`cyhjsrjxgsfhj_yssrbhsje` decimal(20, 2) COMMENT '持有环节收入及相关税费合计_已收收入不含税金额',
`cyhjsrjxgsfhj_yssrse` decimal(20, 2) COMMENT '持有环节收入及相关税费合计_已收收入税额',
`cyhjsrjxgsfhj_srhjjshj` decimal(20, 2) COMMENT '持有环节收入及相关税费合计_收入合计价税合计',
`cyhjszje` decimal(20, 2) COMMENT '持有环节收支净额',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`cyhjsfmx_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '持有环节税费明细';
