CREATE TABLE t_cxs_qlcsyb (
`qlcsyb_id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfhyjfh` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行一级分行',
`dzzcbh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产编号',
`dzzcmc` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产名称',
`dzjehs` decimal(20, 2) COMMENT '抵债金额含税',
`dzhjjxs` decimal(20, 2) COMMENT '抵债环节进项税',
`dzjebhdkjxs` decimal(20, 2) COMMENT '抵债金额不含抵扣进项税',
`cddzhjfwxfdsfjfk` decimal(20, 2) COMMENT '承担抵债环节非我行法定税费及罚款',
`dzhjwxfdsfjfk` decimal(20, 2) COMMENT '抵债环节我行法定税费及罚款',
`cyhjsrhs` decimal(20, 2) COMMENT '持有环节收入含税',
`qtsr` decimal(20, 2) COMMENT '其他收入',
`cyhjcbfy` decimal(20, 2) COMMENT '持有环节成本费用',
`cyhjsfznjjfkzc` decimal(20, 2) COMMENT '持有环节税费滞纳金及罚款支出',
`czskjehsyjwfybkmfcdd` decimal(20, 2) COMMENT '处置收款金额含所有价外费用包括买方承担的',
`czhjwxfdsf` decimal(20, 2) COMMENT '处置环节我行法定税费',
`cdczhjdsffy` decimal(20, 2) COMMENT '承担处置环节第三方费用',
`dzzcqbhjzhsy` decimal(20, 2) COMMENT '抵债资产全部环节综合损益',
`czhjjxjl` decimal(20, 2) COMMENT '处置环节净现金流',
`chzbj` decimal(20, 2) COMMENT '冲回准备金',
`czdqbbsy` decimal(20, 2) COMMENT '处置当期报表损益',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`qlcsyb_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '全流程损益表';
