CREATE TABLE t_cxs_jcxxb  (
`jcxxb _id` BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键',
`zwgsfh` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行',
`zwgsfhmc` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '账务归属分行名称',
`dzzcjbqk_zxzgywbm` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_总行主管业务部门',
`dzzcjbqk_dzzcbh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产编号',
`dzzcjbqk_jjh` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_借据号',
`dzzcjbqk_qy` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_区域',
`dzzcjbqk_fb` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_分部',
`dzzcjbqk_ywjgbm` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_业务经管部门',
`dzzcjbqk_zghr` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_主管户人',
`dzzcjbqk_dzfs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债方式',
`dzzcjbqk_pjshdzxysxr` datetime COMMENT '抵债资产基本情况_判决书或抵债协议生效日',
`dzzcjbqk_qdcqzssj` datetime COMMENT '抵债资产基本情况_取得产权证书时间',
`dzzcjbqk_dzzcdl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产大类',
`dzzcjbqk_dzzcmxfl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产明细分类',
`dzzcjbqk_sl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_数量',
`dzzcjbqk_fcjzmj` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产建筑面积',
`dzzcjbqk_tdxz` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_土地性质',
`dzzcjbqk_tdyt` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_土地用途',
`dzzcjbqk_tdnsdj` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_土地纳税等级',
`dzzcjbqk_tdmj` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_土地面积',
`dzzcjbqk_cyqk` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_持有情况',
`dzzcjbqk_cyqkzyqk_zyrmc` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_持有情况占用情况_占用人名称',
`dzzcjbqk_cyqkzyqk_sfypjcd` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_持有情况占用情况_是否有判决裁定',
`dzzcjbqk_fcszsf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产所在省份',
`dzzcjbqk_fcszs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产所在市',
`dzzcjbqk_fcszxssq` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产所在县市属区',
`dzzcjbqk_fcszxz` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产所在乡镇',
`dzzcjbqk_sfsyjzz` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_是否属于建制镇',
`dzzcjbqk_dzzcmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产名称',
`dzzcjbqk_fczldzgswjg` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_房产坐落地主管税务机关',
`dzzcjbqk_cqssfhzgswjg` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_产权所属分行主管税务机关',
`dzzcjbqk_ycqr` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_原产权人',
`dzzcjbqk_dzzcjkrmc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '抵债资产基本情况_抵债资产借款人名称',
`fyjzwrgt_cdssfmqwxcdycqrsf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_裁定书是否明确我行承担原产权人税费',
`fyjzwrgt_cdsmmqsfcdfsfydycqrsfrdkj` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_裁定书没明确税费承担方时法院对原产权人税费认定口径',
`fyjzwrgt_dfycqrsfnfssqq` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_垫付原产权人税费能否诉讼确权',
`fyjzwrgt_ycqrxz` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_原产权人现状',
`fyjzwrgt_nfqdycqrgrcbzl` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_能否取得原产权人购入成本资料',
`fyjzwrgt_bnqdycqrgrcbzldyy` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '法院及债务人沟通_不能取得原产权人购入成本资料的原因',
`msrgt_czhjsfcdfs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '买受人沟通_处置环节税费承担方式',
`swjgkj_zqdddzzcssyhzchyljskjjzfjl` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_争取到的抵债资产税收优惠政策和有利计税口径及政府奖励',
`swjgkj_swjgdycqrsfcdfrdkj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_税务机关对原产权人税费承担方认定口径',
`swjgkj_wxcdycqrsfznjjfknfsqkc` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_我行承担原产权人税费滞纳金及罚款能否税前扣除',
`swjgkj_dzhjwfqdfpczszzsjtdzzsjskj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_抵债环节无法取得发票处置时增值税及土地增值税计税口径',
`swjgkj_dzhjwfqdfpczsqysdssqkckj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_抵债环节无法取得发票处置时企业所得税税前扣除口径',
`swjgkj_dzhjnsywfssjrdkj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_抵债环节纳税义务发生时间认定口径',
`swjgkj_cyhjnsywfssjrdkj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_持有环节纳税义务发生时间认定口径',
`swjgkj_tdzzsjsfs` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_土地增值税计税方式',
`swjgkj_zzsjsfs` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_增值税计税方式',
`swjgkj_zzsjskj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_增值税计税口径',
`swjgkj_qsjskj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_契税计税口径',
`swjgkj_yhsjskj` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关口径_印花税计税口径',
`swjgsfyqdjyzwrfdzhjsf_sfyqdjqysds` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否要求垫交企业所得税',
`swjgsfyqdjyzwrfdzhjsf_sfyqdjfcs` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否要求垫交房产税',
`swjgsfyqdjyzwrfdzhjsf_sfyqdjtdsys` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否要求垫交土地使用税',
`swjgsfyqdjyzwrfdzhjsf_sfdjtdcrj` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否垫交土地出让金',
`swjgsfyqdjyzwrfdzhjsf_sfdjtdgf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否垫交土地规费',
`swjgsfyqdjyzwrfdzhjsf_sfyqthyzwrqddzfbtjld` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否要求退回原债务人取得的政府补贴奖励等',
`swjgsfyqdjyzwrfdzhjsf_sfjqtsf` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_是否交其他税费',
`swjgsfyqdjyzwrfdzhjsf_smsjyqdjyzwrfdzhjsfdzcyj` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '税务机关是否要求垫交原债务人非抵债环节税费_说明税局要求垫交原债务人非抵债环节税费的政策依据',
`ycqrgt_sfdfhcdsdqjwyglfd` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '原产权人沟通_是否垫付或承担水电气及物业管理费等',
`bz1` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '备注1',
`ssqj` varchar(20)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '所属期间',
`comp_code` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构代码',
`comp_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '机构名称',
`taxpayer_no` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人识别号',
`taxpayer` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '纳税人名称',
`is_valid` tinyint NULL DEFAULT NULL COMMENT '是否有效 0:无效,1:有效[dict:is_valid]',
`enable_status` tinyint NULL DEFAULT NULL COMMENT '启用状态 0:未启用1:已启用[dict:enable_status]',
`create_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人ID',
`create_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '创建人名称',
`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
`update_user_id` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人ID',
`update_user_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '更新人名称',
`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
`tenant_code` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '租户编码',
`reserved1` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段1',
`reserved2` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段2',
`reserved3` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段3',
`reserved4` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段4',
`reserved5` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段5',
`reserved6` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段6',
`reserved7` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段7',
`reserved8` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段8',
`reserved9` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段9',
`reserved10` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '预留字段10'
, PRIMARY KEY (`jcxxb _id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT '基础信息表 ';
