
根据create表结构，把下边查询出来的168行数据，生成168行insert into 的sql;


CREATE TABLE `ec_functiontreenode` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DESCRIPTION` text COLLATE utf8mb4_unicode_ci,
  `TYPE` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RESOURCES` text COLLATE utf8mb4_unicode_ci,
  `AUTHORITYSCRIPT` text COLLATE utf8mb4_unicode_ci,
  `PARENTNODEID` int(10) DEFAULT NULL,
  `ORDERS` int(10) DEFAULT NULL,
  `STATE` int(10) DEFAULT NULL,
  `TREEID` int(10) DEFAULT NULL,
  `MENUTYPE` int(10) DEFAULT NULL,
  `ENTITY` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ICON` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci



MySQL [tms]> select * from ec_functiontreenode;
+----------+--------------------------------------------------------------------+---------------------------------------------+-------------+-----------+------------------------------------------------------+--------------+--------+-------+----------+----------+--------+-----------------------------+
| ID       | NAME                                                               | DESCRIPTION                                 | TYPE        | RESOURCES | AUTHORITYSCRIPT                                      | PARENTNODEID | ORDERS | STATE | TREEID   | MENUTYPE | ENTITY | ICON                        |
+----------+--------------------------------------------------------------------+---------------------------------------------+-------------+-----------+------------------------------------------------------+--------------+--------+-------+----------+----------+--------+-----------------------------+
|       -1 | 基础                                                               | NULL                                        | no-resource | NULL      | NULL                                                 |            0 |      0 |     1 |       -1 |        0 | POIN   | NULL                        |
|    50000 | 平台管理                                                           | 平台管理                                    | vue-node    | NULL      | NULL                                                 |           -1 |     10 |     1 |    50000 |        1 | POIN   | el-icon-monitor             |
|    50002 | 系统参数                                                           | 系统参数                                    | vue-node    | NULL      | NULL                                                 |        50000 |      1 |     1 |    50000 |        2 | POIN   | el-icon-setting             |
|    50003 | 参数管理                                                           | 参数管理                                    | vue         | NULL      | /poinSystem/paramManage                              |        50002 |      3 |     1 |    50002 |        3 | POIN   | NULL                        |
|    50004 | 菜单分配                                                           | 菜单分配                                    | vue         | NULL      | /poinSystem/menuManage                               |        50002 |      4 |     1 |    50002 |        3 | POIN   | NULL                        |
|    50013 | 角色管理                                                           | 角色管理                                    | vue         | NULL      | /poinSystem/roleManage                               |        50002 |      4 |     1 |    50002 |        3 | POIN   | NULL                        |
|    50014 | 组织机构                                                           | 组织机构                                    | vue-node    | NULL      | NULL                                                 |        50000 |      2 |     1 |    50000 |        2 | POIN   | el-icon-connection          |
|    50015 | 用户管理                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |        50014 |      5 |     1 |    50014 |        3 | POIN   | NULL                        |
|    50016 | 机构管理                                                           | NULL                                        | vue         | NULL      | /poinOrganization/orgManage                          |        50014 |      6 |     1 |    50014 |        3 | POIN   | NULL                        |
|    50017 | 部门管理                                                           | NULL                                        | vue         | NULL      | /poinOrganization/departManage                       |        50014 |      7 |     1 |    50014 |        3 | POIN   | NULL                        |
|    50018 | 岗位管理                                                           | NULL                                        | vue         | NULL      | /poinOrganization/postManage                         |        50014 |      8 |     1 |    50014 |        3 | POIN   | NULL                        |
|    50019 | 用户查询                                                           | NULL                                        | vue         | NULL      | /poinOrganization/userManage                         |        50015 |      8 |     1 |    50015 |        4 | POIN   | NULL                        |
|    50020 | 调度任务列表                                                       | NULL                                        | vue         | NULL      | /poinQuartz/schedeulerList                           |        50100 |      1 |     1 |    10100 |        3 | POIN   | NULL                        |
|    50021 | 调度日志查询                                                       | NULL                                        | vue         | NULL      | /poinQuartz/schedulerLog                             |        50100 |      2 |     1 |    10100 |        3 | POIN   | NULL                        |
|    50100 | 调度任务                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |        50000 |      3 |     1 |    50000 |        2 | POIN   | el-icon-set-up              |
|    50101 | 工作流管理                                                         | NULL                                        | vue-node    | NULL      | NULL                                                 |        50000 |      4 |     1 |    50000 |        2 | POIN   | el-icon-connection          |
|    50102 | 流程跟踪                                                           | NULL                                        | vue         | NULL      | /poinWorkflow/processTrace                           |        50101 |      1 |     1 |    50101 |        3 | POIN   | NULL                        |
|    50103 | 流程文件管理                                                       | NULL                                        | vue         | NULL      | /poinWorkflow/wfDefinitionUpload                     |        50101 |      3 |     1 |    50101 |        3 | POIN   | NULL                        |
|    50104 | 流程实例管理                                                       | NULL                                        | vue         | NULL      | /poinWorkflow/processInstance                        |        50101 |      4 |     1 |    50101 |        3 | POIN   | NULL                        |
|    50105 | 流程工作项管理                                                     | NULL                                        | vue         | NULL      | /poinWorkflow/processTask                            |        50101 |      5 |     1 |    50101 |        3 | POIN   | NULL                        |
|    50106 | 流程任务                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |        50101 |      2 |     1 |    50101 |        3 | POIN   | NULL                        |
|    50107 | 我的任务                                                           | NULL                                        | vue         | NULL      | /poinWorkflow/wfassignmentUndo                       |        50106 |      1 |     0 |    50106 |        4 | POIN   | NULL                        |
|    50108 | 我的已办                                                           | NULL                                        | vue         | NULL      | /poinWorkflow/wfassignmentDone                       |        50106 |      2 |     0 |    50106 |        4 | POIN   | NULL                        |
|    50109 | 任务池                                                             | NULL                                        | vue         | NULL      | /poinWorkflow/wfassignmentTask                       |        50106 |      3 |     1 |    50106 |        4 | POIN   | NULL                        |
|    50110 | 流程代理                                                           | NULL                                        | vue         | NULL      | /poinWorkflow/taskAgent                              |        50106 |      4 |     1 |    50106 |        4 | POIN   | NULL                        |
|    50111 | redis监控                                                          | NULL                                        | vue-node    | NULL      | NULL                                                 |        50000 |      5 |     1 |    50000 |        2 | POIN   | el-icon-aim                 |
|    50112 | 数据字典管理                                                       | NULL                                        | vue         | NULL      | /poinSystem/dataDictionaryManage                     |        50002 |      5 |     1 |    50002 |        3 | POIN   | NULL                        |
|    50113 | 键值查询                                                           | NULL                                        | vue         | NULL      | /poinBaseMonitor/keysSearch                          |        50111 |      1 |     1 |    50111 |        3 | POIN   | NULL                        |
|    50114 | 服务端配置                                                         | NULL                                        | vue         | NULL      | /poinBaseMonitor/servers                             |        50111 |      2 |     1 |    50111 |        3 | POIN   | NULL                        |
|    50116 | 用户批处理                                                         | NULL                                        | vue         | NULL      | /poinOrganization/userBatch                          |        50015 |      2 |     1 |    50015 |        4 | POIN   | NULL                        |
|    50124 | 流程管理                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |        50101 |      6 |     1 |    50101 |        3 | POIN   | NULL                        |
|    50125 | 特殊权限配置                                                       | NULL                                        | vue         | NULL      | /poinWorkflow/wfPermissionConfig                     |        50124 |      1 |     1 |    50124 |        4 | POIN   | NULL                        |
|    50126 | 特殊权限管理                                                       | NULL                                        | vue         | NULL      | /poinWorkflow/wfPermissionManage                     |        50124 |      2 |     1 |    50124 |        4 | POIN   | NULL                        |
|    50127 | 待归档管理                                                         | NULL                                        | vue         | NULL      | /poinWorkflow/wfVerifiedManage                       |        50124 |      3 |     1 |    50124 |        4 | POIN   | NULL                        |
|    50128 | 个人流程代理                                                       | NULL                                        | vue         | NULL      | /poinWorkflow/personallyTaskAgent                    |        50124 |      4 |     1 |    50124 |        4 | POIN   | NULL                        |
|    50130 | 流程图编辑                                                         | NULL                                        | vue         | NULL      | /poinWorkflow/wflowChart                             |        50101 |      1 |     1 |    50101 |        3 | POIN   | NULL                        |
|    50300 | 消息队列监控                                                       |                                             | vue-node    | NULL      |                                                      |        50000 |      5 |     1 |    50300 |        1 | POIN   | el-icon-chat-dot-square     |
|    50301 | 运维                                                               |                                             | vue         | NULL      | /poinRocketMq/mqOps                                  |        50300 |      1 |     1 |    50300 |        2 | POIN   | el-icon-postcard            |
|    50302 | 集群                                                               |                                             | vue         | NULL      | /poinRocketMq/mqCluster                              |        50300 |      3 |     1 |    50300 |        2 | POIN   | el-icon-connection          |
|    50303 | 消费者                                                             |                                             | vue         | NULL      | /poinRocketMq/mqConsumer                             |        50300 |      5 |     1 |    50300 |        2 | POIN   | el-icon-film                |
|    50304 | 消息                                                               |                                             | vue         | NULL      | /poinRocketMq/mqMessage                              |        50300 |      7 |     1 |    50300 |        2 | POIN   | el-icon-chat-dot-round      |
|    50305 | 驾驶舱                                                             |                                             | vue         | NULL      | /poinRocketMq/mqDashBoard                            |        50300 |      2 |     1 |    50300 |        2 | POIN   | el-icon-pie-chart           |
|    50306 | 生产者                                                             |                                             | vue         | NULL      | /poinRocketMq/mqProducer                             |        50300 |      6 |     1 |    50300 |        2 | POIN   | el-icon-news                |
|    50400 | 主题                                                               |                                             | vue         | NULL      | /poinRocketMq/mqTopic                                |        50300 |      4 |     1 |    50300 |        2 | POIN   | el-icon-collection-tag      |
|    50404 | 规则管理                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |        50000 |      7 |     1 |    50000 |        2 | POIN   | el-icon-suitcase-1          |
|    50406 | 规则项目管理                                                       | NULL                                        | vue         | NULL      | /poinRuleEngine/ruleManage                           |        50404 |      1 |     1 |    50404 |        3 | POIN   | NULL                        |
|    50408 | 我的规则                                                           | NULL                                        | vue         | NULL      | /poinRuleEngine/myRuleEngine                         |        50404 |      2 |     1 |    50404 |        3 | POIN   | NULL                        |
|   745472 | 登录日志管理                                                       |                                             | vue         | NULL      | /sys-base/data-monitor/login-log                     |     82194176 |      3 |     0 | 82194176 |        2 | POIN   | el-icon-notebook-1          |
|   885504 | 会计凭证明细表                                                     |                                             | vue         |           | /zzs/kjpzmxb/list                                    |     59711744 |      7 |     1 | 59711744 |        3 | POIN   | NULL                        |
|  1592832 | 字典配置                                                           |                                             | vue         | NULL      | /sys-base/dict-manage/list                           |        50002 |      1 |     1 |    50002 |        3 | POIN   | NULL                        |
|  1711616 | 基础设置                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |     66151168 |      1 |     1 | 66151168 |        3 | POIN   | NULL                        |
|  2089472 | 财务数据采集                                                       | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/financialDataCollectionList         |     57343744 |     11 |     1 | 57343744 |        3 | POIN   | NULL                        |
|  3696896 | 我的已办                                                           | NULL                                        | vue         | NULL      | /poinWorkflow/wfassignmentDone                       |     93361664 |     10 |     1 | 93361664 |        3 | POIN   | NULL                        |
|  5399040 | 报表分类管理                                                       |                                             | vue         | NULL      | /tools/report/class/list                             |     17093120 |      3 |     1 | 17093120 |        3 | POIN   | NULL                        |
|  5980160 | 资产分类配置                                                       | NULL                                        | vue         | NULL      | /fctd/zcflpz/list                                    |      1711616 |      2 |     1 |  1711616 |        4 | POIN   | NULL                        |
|  6414336 | 代码表同步                                                         |                                             | vue         | NULL      | /dmbtb/list                                          |        50002 |     10 |     1 |    50002 |        3 | POIN   | NULL                        |
|  8696832 | 科目余额表-月度                                                    |                                             | vue         |           | /zzs/kmyebyd/list                                    |     59711744 |      3 |     1 | 59711744 |        3 | POIN   | NULL                        |
|  9118720 | 业务数据管理                                                       |                                             | vue-node    | NULL      |                                                      |           -1 |      6 |     1 |  9118720 |        1 | POIN   | el-icon-s-data              |
|  9906432 | 对公贷款借据                                                       | NULL                                        | vue         | NULL      | /syncData/ecBgddjList                                |     20722176 |      5 |     1 | 20722176 |        3 | POIN   | NULL                        |
| 10011648 | BW业务表                                                           |                                             | vue         |           | /zzs/bwywb/list                                      |     59711744 |      9 |     1 | 59711744 |        3 | POIN   | NULL                        |
| 11110656 | 同步日志                                                           |                                             | vue         |           | /tool-etl-log/list                                   |     96700672 |      2 |     1 | 96700672 |        3 | POIN   | NULL                        |
| 11193088 | 报表计算周期管理                                                   |                                             | vue         | NULL      | /biz-base/bizbase-period/calculate/list              |     17093120 |     12 |     1 | 17093120 |        3 | POIN   | NULL                        |
| 11972608 | 减免税政策管理                                                     |                                             | vue         | NULL      | /biz-base/reduce-tax-police/all/list                 |      9118720 |      6 |     1 |  9118720 |        2 | POIN   | el-icon-files               |
| 12668928 | 信贷资产损失扣除汇总统计表—贷款分类(管理)                          | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/gdPdDeductionStatisticsTxglList     |     57343744 |      7 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 14016512 | 处置不动产                                                         |                                             | vue         |           | /zzs/chuzhibdc/list                                  |     59711744 |     22 |     1 |  9118720 |        2 | POIN   | el-icon-notebook-2          |
| 15595264 | 核销借据明细表                                                     | NULL                                        | vue         | NULL      | /zcss/hxjjmxb/list                                   |     86735616 |     51 |     1 | 86735616 |        2 | POIN   | NULL                        |
| 15806464 | 操作日志                                                           |                                             | vue         | NULL      | /import-export-config/operation-log/list             |     87109376 |      6 |     1 | 87109376 |        3 | POIN   | NULL                        |
| 15807744 | 纳税主体管理                                                       |                                             | vue         | NULL      | /biz-base/taxpayer-info                              |      9118720 |      1 |     1 |  9118720 |        2 | POIN   | el-icon-service             |
| 16207616 | 纳税主体税种认定管理                                               |                                             | vue         | NULL      |                                                      |      9118720 |      4 |     0 |  9118720 |        2 | POIN   | el-icon-edit-outline        |
| 16222720 | 业务配置                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |     86735616 |     18 |     1 | 86735616 |        2 | POIN   | el-icon-coin                |
| 16862976 | 信贷资产损失扣除汇总统计表—分行(审定)                              | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/gdPdDeductionStatisticsFhsjList     |     57343744 |      8 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 17093120 | 报表指标配置                                                       |                                             | vue-node    | NULL      |                                                      |      9118720 |      2 |     1 |  9118720 |        2 | POIN   | el-icon-bank-card           |
| 18226944 | 凭证管理                                                           | NULL                                        | vue         | NULL      | /assetLosses/gdPingzhList                            |     46804480 |     20 |     1 | 46804480 |        3 | POIN   | NULL                        |
| 19266816 | 科目信息表查询                                                     |                                             | vue         |           | /zzs/kmxxbcx/list                                    |     59711744 |      1 |     1 | 59711744 |        3 | POIN   | NULL                        |
| 19556608 | 核销账户统计表                                                     | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/verificateAccountMainStatisticsList |     57343744 |     11 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 20074496 | 对公贷款账户主表                                                   | NULL                                        | vue         | NULL      | /zcss/dgdkzhzb/list                                  |     62834432 |      1 |     1 | 62834432 |        3 | POIN   | NULL                        |
| 20722176 | 核心业务数据                                                       | NULL                                        | vue-node    | NULL      | NULL                                                 |     86735616 |     25 |     1 | 86735616 |        2 | POIN   | el-icon-c-scale-to-original |
| 20925952 | 属期设置                                                           | NULL                                        | vue         | NULL      | /fctd/sqsz/list                                      |      1711616 |      3 |     1 |  1711616 |        4 | POIN   | NULL                        |
| 21581312 | 零售贷款账户表                                                     | NULL                                        | vue         | NULL      | /zcss/lsywdkzhzb/list                                |     62834432 |      5 |     1 | 62834432 |        3 | POIN   | NULL                        |
| 21633792 | 我的待办                                                           | NULL                                        | vue         | NULL      | /poinWorkflow/wfassignmentUndo                       |     93361664 |      5 |     1 | 93361664 |        3 | POIN   | NULL                        |
| 22119936 | 会计科目                                                           | NULL                                        | vue         | NULL      | /baseFormManagement/accountingSubjectList            |     16222720 |      6 |     1 | 16222720 |        3 | POIN   | NULL                        |
| 23045888 | 变更登记簿                                                         | NULL                                        | vue         | NULL      | /assetLosses/gdBgdjtbList                            |     46804480 |     15 |     1 | 46804480 |        3 | POIN   | NULL                        |
| 26951424 | 表外账明细数据                                                     | NULL                                        | vue         | NULL      | /syncData/ecAbwmxList                                |     20722176 |     20 |     1 | 20722176 |        3 | POIN   | NULL                        |
| 27478016 | IMS发票明细                                                        |                                             | vue         | NULL      | /biz/imsfpmx/list                                    |      9118720 |     15 |     1 |  9118720 |        2 | POIN   | el-icon-notebook-2          |
| 28020992 | 报表展示页面配置                                                   | NULL                                        | vue         | NULL      | /report-config/list                                  |     17093120 |      8 |     1 | 17093120 |        3 | POIN   | NULL                        |
| 28664064 | 实缴税金月度统计表-总行                                            | NULL                                        | vue         | NULL      | /report/manual/10101317/list                         |     40743680 |      3 |     1 | 40743680 |        2 | POIN   | NULL                        |
| 28762624 | 科目余额表-季度                                                    |                                             | vue         |           | /zzs/kmyebjd/list                                    |     59711744 |      5 |     1 | 59711744 |        3 | POIN   | NULL                        |
| 30403328 | 主体与减免项目关系                                                 |                                             | vue         | NULL      | /biz-base/bizbase-taxpayer-break/all                 |      9118720 |      7 |     1 |  9118720 |        2 | POIN   | el-icon-paperclip           |
| 30458624 | 信贷资产损失累计扣除明细情况统计表                                 | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/gdPdAccDeductionList                |     57343744 |     12 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 30477568 | 个人贷款借据                                                       | NULL                                        | vue         | NULL      | /syncData/ecBgrxdList                                |     20722176 |     10 |     1 | 20722176 |        3 | POIN   | NULL                        |
| 31147264 |  科目余额表                                                        | NULL                                        | vue         | NULL      | /baseDataManagement/gdAccountBalance                 |     69008128 |      1 |     0 | 69008128 |        3 | POIN   | NULL                        |
| 31784192 | 批量任务日志                                                       | NULL                                        | vue         | NULL      | /platformManagement/gdBatchLogList                   |        50000 |     10 |     1 |    50000 |        2 | POIN   | el-icon-tickets             |
| 33476352 | 信贷资产损失财务核对表                                             | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/creditAssetsLossList                |     57343744 |     11 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 34873856 | 操作日志                                                           |                                             | vue         | NULL      | /sys-base/data-monitor/audit-log                     |     82194176 |      6 |     0 | 82194176 |        2 | POIN   | el-icon-reading             |
| 35627008 | 实缴税金统计台账                                                   | NULL                                        | vue         | NULL      | /sjsj/sjsjtjtz/list                                  |     40743680 |      1 |     1 | 40743680 |        2 | POIN   | NULL                        |
| 36007680 | 抵债资产对公贷款关联表                                             | NULL                                        | vue         | NULL      | /zcss/lsywdzzc/list                                  |     62834432 |      7 |     1 | 62834432 |        3 | POIN   | NULL                        |
| 36053760 | 属期设置                                                           |                                             | vue         | NULL      | /zzs/sqsz/list                                       |     93516032 |      3 |     1 | 93516032 |        2 | POIN   | el-icon-setting             |
| 37431808 | 期初数据台账                                                       |                                             | vue         | NULL      | /zzs/qcsjtz/list                                     |     93516032 |      8 |     0 | 93516032 |        2 | POIN   | el-icon-coin                |
| 37890048 | 算税过程台账                                                       |                                             | vue         | NULL      | /zzs/ssgctz/list                                     |     93516032 |      6 |     0 | 93516032 |        2 | POIN   | el-icon-coin                |
| 38473728 | 导出配置                                                           |                                             | vue         | NULL      | /import-export-config/export-config/list             |     87109376 |      4 |     1 | 87109376 |        3 | POIN   | NULL                        |
| 39226624 | 核销审定金额                                                       | NULL                                        | vue         | NULL      | /assetLosses/gdHxsdjList                             |     46804480 |     11 |     1 | 46804480 |        3 | POIN   | NULL                        |
| 39244032 | 导入配置                                                           |                                             | vue         | NULL      | /import-export-config/import-config/list             |     87109376 |      2 |     1 | 87109376 |        3 | POIN   | NULL                        |
| 40743680 | 实缴税金管理                                                       | NULL                                        | vue-node    | NULL      | NULL                                                 |           -1 |      8 |     1 | 40743680 |        1 | POIN   | el-icon-s-finance           |
| 46804480 | 资产损失管理                                                       | NULL                                        | vue-node    | NULL      | NULL                                                 |     86735616 |     10 |     1 | 86735616 |        2 | POIN   | el-icon-suitcase-1          |
| 47336960 | 房产基本信息                                                       | NULL                                        | vue         | NULL      | /fctd/fcjbxx/list                                    |     92593152 |      7 |     1 | 92593152 |        4 | POIN   | NULL                        |
| 50988800 | 参数设置                                                           |                                             | vue         | NULL      | /sys-base/parameter-manage/list                      |        50002 |      2 |     1 |    50002 |        3 | POIN   | NULL                        |
| 51097344 | 行政区域                                                           | NULL                                        | vue         | NULL      | /bizData/gdSysAreaList                               |     16222720 |      1 |     1 | 16222720 |        3 | POIN   | NULL                        |
| 51597312 | 信贷资产损失扣除汇总统计表—分行(管理)                              | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/gdPdDeductionStatisticsFhglList     |     57343744 |      6 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 53990912 | 进项税转出台账                                                     |                                             | vue         | NULL      | /zzs/jxszcsj/list                                    |     93516032 |      9 |     0 | 93516032 |        2 | POIN   | el-icon-coin                |
| 54669568 | 信贷资产损失扣除汇总统计表—贷款分类(审定)                          | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/gdPdDeductionStatisticsTxsjList     |     57343744 |      9 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 55010816 | 抵债资产对公贷款关联表                                             | NULL                                        | vue         | NULL      | /zcss/dgdkdzzc/list                                  |     62834432 |      3 |     1 | 62834432 |        3 | POIN   | NULL                        |
| 57343744 | 统计报表                                                           | display:none                                | vue-node    | NULL      | NULL                                                 |     86735616 |     15 |     1 | 86735616 |        2 | POIN   | el-icon-date                |
| 58488576 | 待采集房产信息                                                     | NULL                                        | vue         | NULL      | /fctd/dcjfcxx/list                                   |     92593152 |      2 |     1 | 92593152 |        4 | POIN   | NULL                        |
| 58721024 | 表外分户数据                                                       | NULL                                        | vue         | NULL      | /syncData/ecAbwfhList                                |     20722176 |     15 |     1 | 20722176 |        3 | POIN   | NULL                        |
| 59421184 | wfTest                                                             | NULL                                        | vue         | NULL      | /wftest?processDefId=workflow01                      |     86735616 |     40 |     0 | 86735616 |        2 | POIN   | el-icon-ice-tea             |
| 59702272 | 土地基本信息                                                       | NULL                                        | vue         | NULL      | /fctd/tdjbxx/list                                    |     92593152 |      9 |     1 | 92593152 |        4 | POIN   | NULL                        |
| 59711744 | 数据查询                                                           |                                             | vue-node    |           |                                                      |     93516032 |     25 |     1 | 93516032 |        2 | POIN   | NULL                        |
| 59787776 | 申报事项管理                                                       | NULL                                        | vue         | NULL      | /biz-base/nssbsx-dxl/list                            |      9118720 |     20 |     1 |  9118720 |        2 | POIN   | el-icon-paperclip           |
| 61427200 | 零售核销登记簿                                                     | NULL                                        | vue         | NULL      | /zcss/lsyehxdjb/list                                 |     62834432 |      8 |     1 | 62834432 |        3 | POIN   | NULL                        |
| 62834432 | 新核心业务数据                                                     | NULL                                        | vue-node    | NULL      | NULL                                                 |     86735616 |     50 |     1 | 86735616 |        2 | POIN   | NULL                        |
| 63377664 | 租赁合同信息                                                       | NULL                                        | vue         | NULL      | /fctd/zlhtxx/list                                    |     92593152 |      7 |     1 | 92593152 |        4 | POIN   | NULL                        |
| 63808512 | 纳税主体管理                                                       | NULL                                        | vue         | NULL      | /bizData/gdBizbaseTaxpayerList                       |     16222720 |      3 |     0 | 16222720 |        3 | POIN   | NULL                        |
| 66151168 | 房土税申报                                                         | NULL                                        | vue-node    | NULL      | NULL                                                 |     93516032 |      5 |     1 | 93516032 |        2 | POIN   | NULL                        |
| 66250496 | 报表管理                                                           |                                             | vue         | NULL      | /tools/report/manage/list                            |     17093120 |      6 |     1 | 17093120 |        3 | POIN   | NULL                        |
| 66418176 | 减值准备核算科目                                                   | NULL                                        | vue         | NULL      | /baseFormManagement/gdYwdhpzList                     |     16222720 |      5 |     1 | 16222720 |        3 | POIN   | NULL                        |
| 68829440 | 核销明细管理                                                       | NULL                                        | vue         | NULL      | /assetLosses/verificateAccountSubList                |     46804480 |     10 |     1 | 46804480 |        3 | POIN   | NULL                        |
| 69008128 | 基础数据管理                                                       | NULL                                        | vue-node    | NULL      | NULL                                                 |     86735616 |     35 |     0 | 86735616 |        2 | POIN   | el-icon-files               |
| 69479168 | 统计报表汇总                                                       | NULL                                        | vue         | NULL      | /statisticReport/pageMap                             |     86735616 |     40 |     1 | 86735616 |        2 | POIN   | el-icon-map-location        |
| 71546624 | 信贷资产损失统计表-税务扣除类型维度(管理层数)                      | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/gdPdTaxDeductionList                |     57343744 |     10 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 71955712 | 减值准备核对表                                                     | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/gdPdImpairmentCheckList             |     57343744 |      1 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 72233728 | 抵扣发票台账                                                       |                                             | vue         | NULL      | /zzs/dkfptz/list                                     |     93516032 |     15 |     0 | 93516032 |        2 | POIN   | el-icon-coin                |
| 72809728 | 机构树数据                                                         | NULL                                        | vue         | NULL      | /syncData/glPctreeList                               |     20722176 |     45 |     1 | 20722176 |        3 | POIN   | NULL                        |
| 73119232 | 处置使用过的固定资产                                               |                                             | vue         |           | /zzs/czsygdgdzc/list                                 |     59711744 |     24 |     1 |  9118720 |        2 | POIN   | el-icon-notebook-2          |
| 73208576 | 汇算清缴                                                           | NULL                                        | vue         | NULL      | /assetLosses/settlementPaymentList                   |     46804480 |      6 |     1 | 46804480 |        3 | POIN   | NULL                        |
| 73327104 | 待采集土地信息                                                     | NULL                                        | vue         | NULL      | /fctd/dcjtdxx/list                                   |     92593152 |      1 |     1 | 92593152 |        4 | POIN   | NULL                        |
| 74817792 | 土地等级配置                                                       | NULL                                        | vue         | NULL      | /fctd/tddjpz/list                                    |      1711616 |      1 |     1 |  1711616 |        4 | POIN   | NULL                        |
| 75295488 | 扣除标准管理                                                       | NULL                                        | vue         | NULL      | /baseFormManagement/gdMtListConfList                 |     16222720 |      5 |     1 | 16222720 |        3 | POIN   | NULL                        |
| 75326720 | 零售不良资产登记簿                                                 | NULL                                        | vue         | NULL      | /zcss/lsywblzcdjb/list                               |     62834432 |      6 |     1 | 62834432 |        3 | POIN   | NULL                        |
| 76737792 | 接口报文                                                           |                                             | vue         | NULL      | /jkbw/list                                           |        50002 |     12 |     1 |    50002 |        3 | POIN   | NULL                        |
| 79445504 | 核销账户管理                                                       | NULL                                        | vue         | NULL      | /assetLosses/verificateAccountMainList               |     46804480 |      5 |     1 | 46804480 |        3 | POIN   | NULL                        |
| 79551232 | 税务机关管理                                                       | NULL                                        | vue         | NULL      | /bizData/gdBizbaseTaxofficialList                    |     16222720 |      2 |     0 | 16222720 |        3 | POIN   | NULL                        |
| 82194176 | 系统监控                                                           |                                             | vue-node    | NULL      |                                                      |           -1 |      8 |     1 | 82194176 |        1 | POIN   | el-icon-view                |
| 82229248 | 增值税申报                                                         |                                             | vue         | NULL      | /zzs/zzsnssb/list                                    |     93516032 |      6 |     1 | 93516032 |        2 | POIN   | el-icon-coin                |
| 82703616 | 税企直连初始化                                                     |                                             | vue         | NULL      | /sqzl/csh/list                                       |        50002 |      6 |     1 |    50002 |        3 | POIN   | NULL                        |
| 85182464 | 报表模板适用主体维度信息                                           | NULL                                        | vue         | NULL      | /report-tpl-dimension/list                           |     17093120 |      9 |     1 | 17093120 |        3 | POIN   | NULL                        |
| 85746432 | 申报架构管理                                                       |                                             | vue         | NULL      | /sbjg/list                                           |      9118720 |      0 |     1 |  9118720 |        2 | POIN   | el-icon-setting             |
| 85962496 | 信贷资产核销后收回汇总统计表                                       | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/gdPdWriteOffDataList                |     57343744 |     11 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 86244864 | 内部账明细数据                                                     | NULL                                        | vue         | NULL      | /syncData/ecAnbmxList                                |     20722176 |     30 |     1 | 20722176 |        3 | POIN   | NULL                        |
| 86735616 | 资产损失                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |           -1 |      3 |     1 | 86735616 |        1 | POIN   | el-icon-money               |
| 87038720 | 报表日志管理                                                       | NULL                                        | vue         | NULL      | /bbrzcx/list                                         |     82194176 |     12 |     1 | 82194176 |        2 | POIN   | el-icon-setting             |
| 87109376 | 导入导出配置                                                       |                                             | vue-node    | NULL      |                                                      |        50000 |     16 |     1 |    50000 |        2 | POIN   | el-icon-upload              |
| 87725824 | 导入模板管理                                                       |                                             | vue         | NULL      | /sys-base/import-template/list                       |     82194176 |     15 |     0 | 82194176 |        2 | POIN   | el-icon-upload2             |
| 88059648 | 实缴税金季度统计表-总行                                            | NULL                                        | vue         | NULL      | /report/manual/10101319/list                         |     40743680 |      7 |     1 | 40743680 |        2 | POIN   | NULL                        |
| 90166528 | 信贷资产损失台账                                                   | NULL                                        | vue         | NULL      | /baseDataManagement/gdCrAssLossAccount               |     69008128 |      2 |     0 | 69008128 |        3 | POIN   | NULL                        |
| 90851072 | 信贷资产损失财务明细统计表                                         | display:none;isStatisticReportListData:true | vue         | NULL      | /statisticReport/gdPdFinancialDetailsList            |     57343744 |      5 |     1 | 57343744 |        3 | POIN   | NULL                        |
| 91590912 | 对公不良资产登记簿                                                 | NULL                                        | vue         | NULL      | /zcss/dgdkblzcdjb/list                               |     62834432 |      2 |     1 | 62834432 |        3 | POIN   | NULL                        |
| 92408064 | 出租不动产                                                         |                                             | vue         |           | /zzs/chuzubdc/list                                   |     59711744 |     26 |     1 |  9118720 |        2 | POIN   | el-icon-notebook-2          |
| 92539904 | 接口请求日志                                                       |                                             | vue         | NULL      | /sys-base/data-monitor/interface-log                 |     82194176 |     12 |     1 | 82194176 |        2 | POIN   | el-icon-edit                |
| 92593152 | 台账管理                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |     66151168 |      2 |     1 | 66151168 |        3 | POIN   | NULL                        |
| 92626944 | 算税过程计算表                                                     |                                             | vue         | NULL      |                                                      |     93516032 |      3 |     0 | 93516032 |        2 | POIN   | el-icon-coin                |
| 93361664 | 我的待办                                                           | NULL                                        | vue-node    | NULL      | NULL                                                 |           -1 |      1 |     1 | 86735616 |        2 | POIN   | el-icon-connection          |
| 93516032 | 纳税申报                                                           |                                             | vue-node    | NULL      |                                                      |           -1 |      3 |     1 | 93516032 |        1 | POIN   | el-icon-date                |
| 94595072 | 对公核销登记簿                                                     | NULL                                        | vue         | NULL      | /zcss/dgdkhxdjb/list                                 |     62834432 |      4 |     1 | 62834432 |        3 | POIN   | NULL                        |
| 96273664 | 抽取规则管理                                                       |                                             | vue         |           | /tool-etl-task/list                                  |     96700672 |      1 |     1 | 96700672 |        3 | POIN   | NULL                        |
| 96700672 | 抽取规则                                                           |                                             | vue-node    |           |                                                      |        50000 |     35 |     1 |    50000 |        2 | POIN   | NULL                        |
| 98127872 | 代扣代缴增值税明细                                                 |                                             | vue         |           | /zzs/dkdjzzsmx/list                                  |     59711744 |     11 |     1 | 59711744 |        3 | POIN   | NULL                        |
| 98461440 | 实缴税金月度统计表-分行                                            | NULL                                        | vue         | NULL      | /report/manual/10101318/list                         |     40743680 |      5 |     1 | 40743680 |        2 | POIN   | NULL                        |
| 98795776 | 指标配置                                                           |                                             | vue         | NULL      | /tools/index-definition/list                         |     17093120 |      9 |     1 | 17093120 |        3 | POIN   | NULL                        |
+----------+--------------------------------------------------------------------+---------------------------------------------+-------------+-----------+------------------------------------------------------+--------------+--------+-------+----------+----------+--------+-----------------------------+
